### ISSUE TITLE
Wrong behaviour of kick button!!

### ISSUE THREAD

**Issue by AKACHI-4** [Jdyn/typer-io-web#11]
Hey, In group play mode when new people are added, the player kicking list only shows the current hostname to kick, which is not good website behavior, and when we click on the kick button so the host is get kicked off from the lobby. As per the right behavior Host should have the power to kick others not the host itself get kicked on kicking. 

kindly correct it if you can do it by today.  we have a hackathon and we are using this site for typing activity. If it does react not accordingly so it will be a problematic thing for me. 

if not possible for you just instruct me so I can make some changes there.

**Comment by Jdyn** [comment]
Ooops. Just fixed in 9e89b49
